version: "3.9"
services:
  lomo:
    image: ${IMG}
    container_name: lomorage
    privileged: true
    environment:
      - LOMOD_DISABLE_MOUNT_MONITOR=1
    cap_add:
      - ALL
    volumes:
      - ${HOME_MEDIA_DIR}:/media/primary
      - ${HOME_MEDIA_BAKUP_DIR}:/media/backup
      - ${HOME_LOMO_DIR}:/lomo
      - /dev:/dev
    ports:
      - ${LOMOD_PORT}:${LOMOD_PORT}
    command: $LOMOD_PORT

  watchtower:
    image: ${AUTO_UPDATE_IMG}
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: lomorage --cleanup
